name: Testing
on:
  push:
    branches:
    - master
jobs:
  test:
    name: Testing Swift Package and iOS app
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Force XCode 11.3
        run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
      - name: Testing Swift package
        run: |
		chmod +X .github/scripts/test-swift.sh 
	  	exec ./.github/scripts/test-swift.sh
      - name: Testing iOS app
        run: |
          	chmod +X .github/scripts/test-app.sh 
	  	exec ./.github/scripts/test-app.sh
