name: Testing
on:
  pull_request:
    branches:
    - master
jobs:
  test:
    name: Testing Swift Package and iOS app
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Force XCode 16.2
        run: sudo xcode-select -switch /Applications/Xcode_16.2.app
      - name: Testing Swift package
        run: exec ./.github/scripts/test_swift-package.sh
      - name: Testing iOS app
        run: exec ./.github/scripts/test-app.sh
